### PR TITLE
Fix bug in default readable output port

### PR DESCRIPTION
**Pull request by bertfrees**
I don't know exactly what I have done because I don't really understand the code, but it seems to work.

### CODE REVIEW

**Review by rdeltour — COMMENTED** [review]
> I don't know exactly what I have done because I don't really understand the code

Haha :-) 
This PR is a bit difficult to review since I don't know exactly what is the bug that is supposed to be fixed. Do you have a test case?

**Comment by bertfrees** [comment]
Test case is a good idea.

**Comment by bertfrees** [comment]
See https://github.com/ndw/xmlcalabash1/pull/306.

**Comment by bertfrees** [comment]
I spent some time trying to reproduce the issue with a simple test case but I didn't manage to. I was hoping I would get some clues from upstream but there is no reaction on my [pull request](https://github.com/ndw/xmlcalabash1/pull/306).

I decided to just merge it (see bbcb39f) because I have to move on and I'm not seeing any negative side effects.

**Pull request closed without merging**
